name: Build and Publish to GHCR

on:
  push:
    branches:
      -main

jobs:
  push-image:
    runs-on: "ubuntu-latest"


    steps:
      - uses: actions/checkout@v5

      - name: Build and Push Docker Image
        uses: macbre/push-to-ghrc@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          image_tag: latest